### ISSUE TITLE
租户隔离方面如何考虑？

### ISSUE THREAD

**Issue by xewn** [hey-hoho/ScheduleMasterCore#1]
多租户使用一个任务调度，不同租户的数据是独立处理？还是不管租户的概念一起处理？
或者说如何能够降低租户之间的互相影响呢？

**Comment by hey-hoho** [comment]
你这里的多租户具体是指什么？如果是多个任务的话已经是互相隔离的，不会有影响

**Comment by xewn** [comment]
客户=租户，不同的客户就是不同的租户。A租户的job和B租户的job完全隔离？

**Comment by hey-hoho** [comment]
@xewn 暂不考虑做租户隔离，感谢支持。
