### ISSUE TITLE
对于数据库区分大小写的，自动生成的模型是包含大小写的，有部分sql使用了全小写的表名执行不通过。

### ISSUE THREAD

**Issue by firefly1513** [hey-hoho/ScheduleMasterCore#11]
详见 RootJob.cs 文件下的38，89，120行

private void UpdateRunTrace(Guid traceId, double elapsed, ScheduleRunResult result)
        {
            if (traceId == Guid.Empty) return;
            _db.Database.ExecuteSqlRaw($"update scheduletraces set result={(int)result},elapsedtime={elapsed},endtime=now() where traceid='{traceId}'");
        }

**Comment by hey-hoho** [comment]
感谢您的指出，麻烦提供一下您的运行环境我作为参考进行问题排查。

**Comment by hey-hoho** [comment]
fixed #11
