### ISSUE TITLE
执行的任务依赖其他 dll 时如何处理

### ISSUE THREAD

**Issue by renqiancheng** [hey-hoho/ScheduleMasterCore#14]
你好，请教一下：

当执行的任务逻辑比较复杂，涉及引用第三方 dll 时，一起打包的依赖 dll 不会下发给 work。

即使手动复制到 work 相应的插件路径 .\wwwroot\plugins\xxxx-xxxx-xxxx 下也不会生效。

![Snipaste_2020-03-13_22-05-52](https://user-images.githubusercontent.com/1492406/76627906-db6b2580-6576-11ea-9064-19fa86b34e1b.png)

**Comment by hey-hoho** [comment]
你好，看一下日志里面有没有异常信息和堆栈，你这种情况应该是启动任务时候worker拉取程序包失败导致。业务引用其他dll的时候一起打包进去就行的

**Comment by renqiancheng** [comment]
谢谢！确实是可以的，这里记录下出现问题的原因：
① 一定要注意压缩的文件包要以任务的程序集名称命名。
② 打包的文件里面不要包含 Hos.ScheduleMaster.Base.dll 。
