### ISSUE TITLE
是否支持引用了连接数据库类库 Microsoft.Data.SqlClient 的服务？

### ISSUE THREAD

**Issue by renqiancheng** [hey-hoho/ScheduleMasterCore#17]
请教一下：

服务中如果连接数据库引用了 Microsoft.Data.SqlClient 或者 System.Data.SqlClient 就会执行失败，是添加的方式不对吗？

> 错误信息：Microsoft.Data.SqlClient is not supported on this platform.

![image](https://user-images.githubusercontent.com/1492406/77508135-e8f0ab80-6ea4-11ea-8354-d91ced83f908.png)
![image](https://user-images.githubusercontent.com/1492406/77508200-1b020d80-6ea5-11ea-81a2-377f7124bcbf.png)

**Comment by hey-hoho** [comment]
应该是你程序集版本有问题导致的，检查一下
