### ISSUE TITLE
多个任务使用同一个dll的时候下载时报错的解决方法

### ISSUE THREAD

**Issue by jiancaixing** [hey-hoho/ScheduleMasterCore#18]
var sourcePath = $"{master.AccessProtocol}://{master.Host}/static/downloadpluginfile?pluginname={model.AssemblyName}";
            var timeSpan = DateTime.Now.ToString("yyyyMMddHHmmssfff");
           var zipPath = $"{ConfigurationCache.PluginPathPrefix}\\{model.AssemblyName}{timeSpan}.zip".ToPhysicalPath();
            var pluginPath = $"{ConfigurationCache.PluginPathPrefix}\\{model.Id}".ToPhysicalPath();
            using (WebClient client = new WebClient())
            {
                try
                {
                    await client.DownloadFileTaskAsync(new Uri(sourcePath), zipPath);
                }
                catch (Exception ex)
                {
                    LogHelper.Warn($"下载程序包异常，地址：{sourcePath}", model.Id);
                    throw ex;
                }
            }
            //将指定 zip 存档中的所有文件都解压缩到各自对应的目录下
            ZipFile.ExtractToDirectory(zipPath, pluginPath, true);
            System.IO.File.Delete(zipPath);

**Comment by jiancaixing** [comment]
var zipPath = $"{ConfigurationCache.PluginPathPrefix}\\{model.AssemblyName}{timeSpan}.zip".ToPhysicalPath();   加上个时间标识就可以解决这个问题

**Comment by jiancaixing** [comment]
guid更好，肯定不会重复

**Comment by hey-hoho** [comment]
感谢您的反馈，下个版本会修复这个问题。

**Comment by hey-hoho** [comment]
另外，这部分加了一个新特性，支持配置文件包拉取策略，敬请关注。😀
