### ISSUE TITLE
docker 部署出现错误

### ISSUE THREAD

**Issue by junbao520** [hey-hoho/ScheduleMasterCore#20]
响应码：500，请求地址：http://localhost:30002/health，响应消息：Cannot assign requested address Cannot assign requested address

通过浏览器访问 http://localhost:30002/health 是可以访问成功的。

还想请教您一下是什么问题导致的？

**Comment by hey-hoho** [comment]
看一下你的节点管理页面，以及执行的docker命令

**Comment by junbao520** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"HOHO"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月21日(星期二) 下午4:19
收件人:&nbsp;"hey-hoho/ScheduleMasterCore"<ScheduleMasterCore@noreply.github.com&gt;;
抄送:&nbsp;"等待。情缘"<757114760@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [hey-hoho/ScheduleMasterCore] docker 部署出现错误 (#20)





 
看一下你的节点管理页面，以及执行的docker命令

**Comment by junbao520** [comment]
执行的docker 命令就是按照
您的文章上面的命令执行的！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"HOHO"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月21日(星期二) 下午4:19
收件人:&nbsp;"hey-hoho/ScheduleMasterCore"<ScheduleMasterCore@noreply.github.com&gt;;
抄送:&nbsp;"等待。情缘"<757114760@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [hey-hoho/ScheduleMasterCore] docker 部署出现错误 (#20)





 
看一下你的节点管理页面，以及执行的docker命令

**Comment by junbao520** [comment]
![image](https://user-images.githubusercontent.com/20721833/79843990-9f38a980-83ed-11ea-8b9b-9fcfdd7c6002.png)
节点管理页面

**Comment by hey-hoho** [comment]
进QQ群来聊824535095
