### ISSUE TITLE
Google浏览器登录

### ISSUE THREAD

**Issue by JosonJiang** [hey-hoho/ScheduleMasterCore#25]
http://localhost:30000/Login/Index
无法登陆 成功后也没不跳转，火狐测试没问题

Google Chrome
版本 81.0.4044.138（正式版本） （64 位）

**Comment by hey-hoho** [comment]
看一下浏览器控制台中的具体报错信息

**Comment by JosonJiang** [comment]
> 看一下浏览器控制台中的具体报错信息

 可以了 清理浏览器缓存好了，以前输入错误账号密码 提示 错误，正确账号密码就页面刷新下完了
