### ISSUE TITLE
数据库初始化脚本中乱码 

### ISSUE THREAD

**Issue by JosonJiang** [hey-hoho/ScheduleMasterCore#26]
ModelBuilderExtensions 文件中的数据好像没有起作用

==============================================
systemusers  初始化脚本没有数据 无法登录，需要自己添加用户

systemconfigs 脚本中乱码（编码不是 utf-8 ，而且 还原数据库时不能选中为 utf-8）

'Assembly_ImagePullPolicy', '³ÌÐò¼¯ÅäÖÃ', 'ÎÄ¼þ°üÀ­È¡²ßÂÔ', 'IfNotPresent', '1', '1', 'Always-×ÜÊÇÀ­È¡£¬IfNotPresent-±¾µØÃ»ÓÐÊ±À­È¡£¬Ä¬ÈÏÊÇAlways', '2020-04-05 08:57:18.417000', '2020-04-05 17:12:09.487020', 'admin'
'Email_FromAccount', 'ÓÊ¼þÅäÖÃ', '·¢¼þÈËÕËºÅ', '', '3', '1', 'seed by efcore auto migration', '2020-04-05 15:38:14.583060', '2020-04-05 17:12:09.492483', 'admin'
'Email_FromAccountPwd', 'ÓÊ¼þÅäÖÃ', '·¢¼þÈËÕËºÅÃÜÂë', '', '4', '1', 'seed by efcore auto migration', '2020-04-05 15:38:14.583060', '2020-04-05 17:12:09.493020', 'admin'
'Email_SmtpPort', 'ÓÊ¼þÅäÖÃ', 'ÓÊ¼þ·þÎñÆ÷¶Ë¿Ú', '25', '2', '1', 'seed by efcore auto migration', '2020-04-05 15:38:14.583053', '2020-04-05 17:12:09.491849', 'admin'
'Email_SmtpServer', 'ÓÊ¼þÅäÖÃ', 'ÓÊ¼þ·þÎñÆ÷', '', '1', '1', 'seed by efcore auto migration', '2020-04-05 15:38:14.582863', '2020-04-05 17:12:09.491180', 'admin'
'Http_RequestTimeout', 'HTTPÅäÖÃ', 'ÇëÇó³¬Ê±Ê±¼ä', '10', '1', '1', 'µ¥Î»ÊÇÃë£¬Ä¬ÈÏÖµÊÇ10', '2020-04-08 06:48:48.201000', NULL, NULL
'System_WorkerUnHealthTimes', 'ÏµÍ³ÅäÖÃ', 'WorkerÔÊÐíÎÞÏìÓ¦´ÎÊý', '3', '1', '1', '½¡¿µ¼ì²éÊ§°Ü´ïµ½×î´ó´ÎÊý»á±»ÏÂÏßÌÞ³ý£¬Ä¬ÈÏÖµÊÇ3', '2020-04-08 06:48:48.201000', NULL, NULL

**Comment by hey-hoho** [comment]
乱码问题检查下数据库默认的编码类型，初始数据没创建的话可以先把数据库手动删除再尝试重新迁移看看

**Comment by JosonJiang** [comment]
> 乱码问题检查下数据库默认的编码类型，初始数据没创建的话可以先把数据库手动删除再尝试重新迁移看看

直接看ModelBuilderExtensions 文件中的 在数据库中改好了
