### ISSUE TITLE
AccessControlFilter 是不是有点问题？

### ISSUE THREAD

**Issue by JosonJiang** [hey-hoho/ScheduleMasterCore#27]

**Comment by JosonJiang** [comment]
AccessControlFilter 是不是有点问题？

`
        public void OnActionExecuting(ActionExecutingContext context)
        {
            //var conn = _accessor.HttpContext.Connection;
            //if (conn.RemoteIpAddress.Equals(conn.LocalIpAddress))
            //{
            //    //同域请求不做验证
            //    return;
            //}
            string userName = context.HttpContext.Request.Headers["ms_auth_user"].FirstOrDefault();
            string secret = context.HttpContext.Request.Headers["ms_auth_secret"].FirstOrDefault();
            if (!string.IsNullOrEmpty(userName) && !string.IsNullOrEmpty(secret))
            {

               // return;

                var user = _account.GetUserbyUserName(userName);
                if (user != null && user.Status == (int)SystemUserStatus.Available)
                {
                    string se = SecurityHelper.MD5($"{userName}{user.Password}{userName}");
                    if (se == secret) return;
                }
            }
            context.Result = new UnauthorizedResult();
        }

`

account.GetUserbyUserName(userName);  执行后报未将对象引用到实例，

看了下具体原因是 _repositoryFactory 和 _unitOfWork 都是 null

**Comment by JosonJiang** [comment]
`
        /// <summary>
        /// 使用用户名查找用户
        /// </summary>
        /// <param name="name"></param>
        /// <returns></returns>
        public SystemUserEntity GetUserbyUserName(string name)
        {
            return _repositoryFactory.SystemUsers.FirstOrDefault(x => x.UserName == name && x.Status != (int)SystemUserStatus.Deleted);
        }

`


  _repositoryFactory  为 null 报错了

**Comment by hey-hoho** [comment]
拉取一下最新代码

**Comment by JosonJiang** [comment]
> 拉取一下最新代码

代码已更新，可是 非http的任务都无法启动了 

调试 好像是 401原因
