### ISSUE TITLE
cpu 内存占用率过高

### ISSUE THREAD

**Issue by chengxianglian** [hey-hoho/ScheduleMasterCore#28]
一共只跑了8个任务，其中6个是5秒一次；1个任务2秒一次；7个任务中有时候回超时导致任务失败，这是api本身的问题与框架无关。
但是cpu和内存这么高我不理解，难道api超时时或者请求频率过高时，框架本身哪里需要很高的内存或者cpu吗？刚开始的时候是开了两个worker cpu直接100%打满了，而且其中一个worker根本就没有去调度任务去工作，一直处于空闲状态。 服务器环境是window server 2016 ! 跪求修复方案
![image](https://user-images.githubusercontent.com/16663102/84366529-88504f80-ac05-11ea-8c61-a6a7057c51b8.png)

![image](https://user-images.githubusercontent.com/16663102/84366268-2abc0300-ac05-11ea-9c77-2b6fdbc5ee5c.png)

**Comment by hey-hoho** [comment]
1、从你的描述看，都是HTTP任务在运行吗，接口响应时间大概是多少
2、worker一启动就直接CPU100%吗，有没有更详细的监控信息
3、看你的任务都指定了2个worker节点，那么每次执行只会有一个执行成功这是正常的，你说的没有执行调度的worker应该是竞争失败了，你可以根据worker名称去查一下日志表进一步排查
4、框架本身没有特别消耗CPU和内存的地方，关于你的服务器信息和部署方式麻烦再详细描述下

感谢您的反馈.

**Comment by heyz** [comment]
1、是的所有任务全是http任务
2、worker不是一启动cpu就100%，是运行一段时间之后。因为只是http请求，shedulemaster已经包含了请求时间与返回结果的监控信息，所以没有更多的监控信息。
3、是的其中一个worker竞争失败，而且是长时间的失败；问题就在这里了worker竞争失败了cpu也占百分之40几！ worker除了去竞争之外没有去调度任务，也没有其他额外消耗， 为什么cpu还会这么高？
4、window server 2016 DataCenter 64位   8G内存  2.5GHZ   动态参数启动。 因为是Sqlserver 2008R2的数据库所以EF版本降低到了 2.2.6
5、刚又试了一下重启一个worker 刚启动新worker的cpu就达到了百分之四十几！ 这有点怪怪的

**Comment by nythma** [comment]
关注下，解决好了，同步下原因，谢谢。

**Comment by hey-hoho** [comment]
@chengxianglian 新版本已经优化了内存占用问题，可以关注下。

参考你给的用例，10个http任务每2秒执行一次，初期会有一个内存增加阶段，增加到120M左右开始下降，后持续稳定在80M左右，CPU占用不会超过2%，win10专业版64位系统，6C16G配置。
![image](https://user-images.githubusercontent.com/8401517/85522978-f13dbb80-b638-11ea-8f74-219e3d54f585.png)
