### ISSUE TITLE
Api创建任务异常信息

### ISSUE THREAD

**Issue by nodyang** [hey-hoho/ScheduleMasterCore#29]
![image](https://user-images.githubusercontent.com/3090191/84991229-d2db4a00-b178-11ea-9ed2-562d3b0cbd0c.png)
![image](https://user-images.githubusercontent.com/3090191/84991257-dd95df00-b178-11ea-9aa6-688bf61021c3.png)
at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Hos.ScheduleMaster.QuartzHost.Common.HosScheduleFactory.ConvertParamsJson(String source) in /home/nodyang/working/ScheduleMasterCore/src/ScheduleMasterCore/Hos.ScheduleMaster.QuartzHost/Common/HosScheduleFactory.cs:line 99

**Comment by nodyang** [comment]
List<KeyValuePair<string, string>> keyValuePairs = new List<KeyValuePair<string, string>>();
            keyValuePairs.Add(new KeyValuePair<string, string>("MetaType", "2"));
            keyValuePairs.Add(new KeyValuePair<string, string>("RunLoop", "true"));
            keyValuePairs.Add(new KeyValuePair<string, string>("CronExpression", "0 */10 * * * ?"));
            keyValuePairs.Add(new KeyValuePair<string, string>("Remark", "青岛远洋购供应链有限公司-美亚购-平台申报"));
            keyValuePairs.Add(new KeyValuePair<string, string>("StartDate", DateTime.Today.ToString("yyyy-MM-dd HH:mm:ss")));
            keyValuePairs.Add(new KeyValuePair<string, string>("Title", "Http接口测试任务"));
            keyValuePairs.Add(new KeyValuePair<string, string>("HttpRequestUrl", "http://www.baidu.com/"));
            keyValuePairs.Add(new KeyValuePair<string, string>("HttpMethod", "POST"));
            keyValuePairs.Add(new KeyValuePair<string, string>("HttpContentType", "application/x-www-form-urlencoded"));
            keyValuePairs.Add(new KeyValuePair<string, string>("HttpHeaders", "[]"));
            keyValuePairs.Add(new KeyValuePair<string, string>("RunNow","true"));

**Comment by hey-hoho** [comment]
参数加上：keyValuePairs.Add(new KeyValuePair<string, string>("HttpBody", "[]"));

json格式参数的话httpbody字段可以为空，如果是form格式参数就必须传入这个字段的固定格式（json数组）

**Comment by nodyang** [comment]
好来。3Q
