### ISSUE TITLE
自定义设置http超时时间

### ISSUE THREAD

**Issue by heyz** [hey-hoho/ScheduleMasterCore#31]
框架中默认设置10秒为http请求的超时时间；
在全局设置中可以设置全局的http请求超时时间，然后却没有单个任务http请求的超时时间设置。
在实际的调度任务中会针对单个任务来设置，例如 ：
  【任务1】 每5秒请求一次， 可以设置这个任务的超时时间为5秒钟；
  【任务2】 每10秒请求一次，可以设置这个任务超时时间为10秒钟；
阅读源码后发现其实要实现这个功能非常简单，在需要在httpSchedule文件中的HttTask构造方法中添加如下代码：
![image](https://user-images.githubusercontent.com/10278218/86221836-ff02bc00-bbb7-11ea-9f54-14724ce32163.png)

【timeout】 是配置任务时的Http请求header，这也是因为作者你在这里获取了header对象，非常容易操作！

**Comment by hey-hoho** [comment]
感谢您的建议，会考虑在下次更新中添加进去。
