### ISSUE TITLE
http任务bug

### ISSUE THREAD

**Issue by xfeMr3** [hey-hoho/ScheduleMasterCore#39]
bug描述：http任务，请求方式为httpget, 创建任务时数据格式选择json-data, 由于是get请求所以数据内容不填。此种任务启动失败。
bug分析：异常在HttpTask类以下代码上抛出
` 
               if (httpOption.ContentType == "application/json")
                {
                    requestBody = httpOption.Body.Replace("\r\n", "");
                }
`
推测httpOption.Body应该是null，此时去查看数据库表 schedulehttpoptions 发现 body字段确实为 null

**Comment by hey-hoho** [comment]
感谢您的反馈，我会在后续更新中修复这个问题。
