### ISSUE TITLE
关于quartz.net结合官方提供的dbstore的疑问

### ISSUE THREAD

**Issue by djl394922860** [hey-hoho/ScheduleMasterCore#43]
首先感谢作者在空闲时间对这个项目的付出 , 针对题目我有一些疑问希望跟作者共同探讨...

1. 我观察到最新release代码以及结合架构示意图得知 , 每一个work都会初始化一个quartz调度器 , 那么就会导致多个quartz调度器抢占式的去执行job , 我看到 RootJob 打上了标签 [DisallowConcurrentExecution] ( 根据文档得知其具体是根据 jobdetail来控制并发执行的 , 不是job实现类的实例 ) 来实现单个quartz调度中的防止同一时刻并发执行同一个job(相同的jobdetail) , 但是如果是多个quartz调度器的情况 , 所以我看到在执行中的另外通过dblock( DatabaseLock )来实现竞态问题

我想知道的是您有实验过直接使用dbstore来存储quartz的数据 , 然后多个worker共享db来实现上述的问题吗?( 其实内部也是采用dblock的方式 )

2. 多个quartz调度器共同工作下的任务负载有相关的设计考虑和实现吗?

再次感谢您的开源付出!!!

**Comment by hey-hoho** [comment]
感谢您对项目的关注。

1、多个quartz实例的竞争问题是通过分布式锁来解决的，目前项目使用的就是基于数据库乐观锁的一种方案，quartz官方的持久化和集群模式也是使用类似方案，在数据库没有性能瓶颈的情况下该方案简单可靠，比较容易实现，开发过程中通过了大量的测试。后期计划中也考虑引入redis分布式锁，但是现阶段项目对redis的需求不是很大，为了简化部署能快速上手使用，该计划暂时会后延。
2、关于任务负载没有太理解，能否具体描述一下？

**Comment by djl394922860** [comment]
> 感谢您对项目的关注。
> 
> 1、多个quartz实例的竞争问题是通过分布式锁来解决的，目前项目使用的就是基于数据库乐观锁的一种方案，quartz官方的持久化和集群模式也是使用类似方案，在数据库没有性能瓶颈的情况下该方案简单可靠，比较容易实现，开发过程中通过了大量的测试。后期计划中也考虑引入redis分布式锁，但是现阶段项目对redis的需求不是很大，为了简化部署能快速上手使用，该计划暂时会后延。
> 2、关于任务负载没有太理解，能否具体描述一下？

关于第二点 , 我看到了是通过worker的priority来选择执行worker的 , 也就是人工选择job的执行负载的机器 , 我理解了

外加我准备吸取您的项目的思想 , 开展公司的任务调度平台的建设 , 希望有机会提交PR , 加油

再次感谢您的开源项目
