### ISSUE TITLE
分布式是如何保证的?

### ISSUE THREAD

**Issue by taadis** [hey-hoho/ScheduleMasterCore#5]

**Comment by hey-hoho** [comment]
请详细描述下你的问题，感谢关注。

**Comment by taadis** [comment]
额 任务的怎么保证分布式一致性的？

**Comment by hey-hoho** [comment]
你的意思是指如何保证多节点下任务只被执行一次吗？目前是通过数据库乐观锁实现

**Comment by taadis** [comment]
依赖数据库乐观锁? 我印象中 Quartz 本身好像也是通过这种方式.

**Comment by hey-hoho** [comment]
是的，原生的Quartz是也是这种方式，我是自己另外实现的，没有使用自带的集群模式

**Comment by taadis** [comment]
好的. 另一个疑问是比如现在新增了一个 job, 是怎么分发到各个节点上去的?

**Comment by hey-hoho** [comment]
参考文章：https://www.cnblogs.com/hohoa/p/12197518.html
里面详细说了启动流程。

**Comment by taadis** [comment]
正巧在看. 建议把文档也理一份出来放到项目 docs 里.

**Comment by hey-hoho** [comment]
最近正在补文档，后面会整理好统一放到github上。
