### ISSUE TITLE
使用docker 发布运行程序错误

### ISSUE THREAD

**Issue by cgrain1998** [hey-hoho/ScheduleMasterCore#63]
![image](https://user-images.githubusercontent.com/35121432/126430007-c4cb38b9-a6f3-4ce1-8c13-4dd36b522cae.png)
这是使用docker 在同一个网段来进行发布的

开启关闭 子node 没问题
![image](https://user-images.githubusercontent.com/35121432/126430051-e1060b76-677f-4cee-82a1-5b41ff23255e.png)

下载程序包有问题
![image](https://user-images.githubusercontent.com/35121432/126430094-b3be47e8-b793-4483-82fa-379c0eb13631.png)

**Comment by cgrain1998** [comment]
主Master 
![image](https://user-images.githubusercontent.com/35121432/126430606-aef77095-9a73-4041-84b7-9b6a5b1ac463.png)

子 node
![image](https://user-images.githubusercontent.com/35121432/126430526-f192f555-8b96-4e65-83d0-cc6399ea57be.png)

**Comment by hey-hoho** [comment]
这样排查一下：
- 程序包是否正常上传了
- master节点检查下/wwwroot/plugins目录是否有上传的程序包
- 目录权限是否给够了

**Comment by cgrain1998** [comment]
大哥, 不好意思又给你提了个bug
自己写的 dll有问题,用你默认的没问题,我在试试

**Comment by hey-hoho** [comment]
没关系，有问题可以多讨论
