### ISSUE TITLE
轻量级的话建议数据库默认使用sqlite

### ISSUE THREAD

**Issue by TomLiu-GitHub** [hey-hoho/ScheduleMasterCore#64]
轻量级的话建议数据库默认使用sqlite

**Comment by hey-hoho** [comment]
感谢您的建议，早期为了部署方便确实想过使用sqlite，后面考虑到功能迭代方面sqlite无法满足所以使用了mysql，尽管项目不大但对于一个分布式系统来说使用一款成熟且主流的数据库还是有必要的。
