### ISSUE TITLE
部署多个节点的时候，如果一个节点的服务器时间跑的快一点，会一直在那个节点运行

### ISSUE THREAD

**Issue by yinguanhua** [hey-hoho/ScheduleMasterCore#65]
这样选择多个节点的话会导致，全部运行都在同一个节点，导至另一个节点没有服务运行，不能负载均衡

**Comment by hey-hoho** [comment]
分布式系统的基石就是必须所有节点要时间同步，避免出现不可预知的问题。

**Comment by gitlsl** [comment]
@hey-hoho   这么好的项目咋不继续更新了。。。

**Comment by hey-hoho** [comment]
> @hey-hoho 这么好的项目咋不继续更新了。。。

@gitlsl 因为工作原因现在换了技术领域，很多东西要学习实在难以抽开身，但是这个项目我没有放弃持续在跟进使用情况，.NET也一直在关注，预计近期会针对.NET6做一次升级，感谢关注~
